# Generated by Django 6.0.3 on 2026-03-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='additional_docs',
            field=models.FileField(blank=True, null=True, upload_to='documents/additional/', verbose_name='Дополнительные документы'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='documents/passports/', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='snils',
            field=models.CharField(max_length=14, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='snils_scan',
            field=models.FileField(blank=True, null=True, upload_to='documents/snils/', verbose_name='Скан СНИЛС'),
        ),
    ]
