# Generated by Django 6.0.3 on 2026-04-08 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_citizen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История заявки', 'verbose_name_plural': 'История заявок'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.RemoveField(
            model_name='operator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='operator',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='socialapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='socialapplication',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AddField(
            model_name='socialapplication',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='action',
            field=models.CharField(max_length=200, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.socialapplication', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Старый статус'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный оператор'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='description',
            field=models.TextField(verbose_name='Описание проблемы/запроса'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='service_type',
            field=models.CharField(default='Ежемесячная денежная выплата', max_length=200, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'На рассмотрении'), ('completed', 'Выполнена'), ('rejected', 'Отказано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
