# Generated by Django 6.0.3 on 2026-04-08 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_applicationhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='operator',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='socialapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socialapplication',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='socialapplication',
            name='phone',
        ),
        migrations.AddField(
            model_name='citizen',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='operator',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='operator',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='operator',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.socialapplication'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='service_type',
            field=models.CharField(max_length=200, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'На рассмотрении'), ('completed', 'Выполнена'), ('rejected', 'Отказано')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
